### ISSUE TITLE
How to find out the amount of data your page is using?

### ISSUE THREAD

**Issue by K135** [tanaypratap/ama#1]
https://k135.github.io/worldt/

Sir Can u tell me how much data does it consume ? 
Because this is a small part of my app something like world tour..

And it's hosted in github and github gives only 1 GB bandwidth per month

Will it be able to be accessed by 1000's through out ?

**Comment by tanaypratap** [comment]
Try this
https://chrome.google.com/webstore/detail/page-size-inspector/oepnndnpjiahgkljgbohnnccmokgcoln

or learn about network panel in chrome

**Comment by tanaypratap** [comment]
Once you have the page size say, `pageSize`
Total number of users, `totalUsers`
then total bandwidth is `bandWidth = pageSize * totalUsers`

@K135 hope this helps?

**Comment by tanaypratap** [comment]
@K135 check #26 as well. It's an extension to your question.
