### ISSUE TITLE
Necessity of doing masters in the related field

### ISSUE THREAD

**Issue by Manish-M2018** [tanaypratap/ama#110]
Hi,
I wanted to know whether it is necessary to do masters in the field that we want to enter? Like for data science or is masters just a waste of time?
Please give your opinion on the same.

**Comment by prerana1821** [comment]
Hey @Manish-M2018,
Tanay as made recently made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/JbGjZk_EQpg
If you have more questions on this topic feel free to comment on the video.
Thanks :)
