### ISSUE TITLE
Is MKCL's worth learning ?

### ISSUE THREAD

**Issue by Shrinesh** [tanaypratap/ama#114]
Hi, sir,
I am Shrinesh, passed 10th SSC board exam and moving on to 11th now, as I am still a student and my dream is to be a programmer I want to learn computer languages.
    I found this in my locals where a computer institute (not so big or renowned, in a village), which offers MKCL'S courses and one of them is where it's been taught C,C++, Scratch and web development... I want to know is it worth learning there , and is MKCL good and offers valued courses ?

**Comment by tanaypratap** [comment]
What's MKCL?

**Comment by Shrinesh** [comment]
A Brand providing courses to learn at local net cafe's. I sent this mail a
long ago... And please don't worry about trying to get knowledge about it
sir, as I now know that it's waste of time

**Comment by Shrinesh** [comment]
And money too

**Comment by tanaypratap** [comment]
Good. Thanks. Closing this issues.
