### ISSUE TITLE
If I have a hectic job how do I find the time to learn outside it?

### ISSUE THREAD

**Issue by examin** [tanaypratap/ama#12]
How do you separate time from work to learn. I always find myself working on my job tasks and yes i work on weekends and even after working hours. Because of this i find very less time to attend meetups or learn concepts. yes the office work i do is interesting, but they want me to complete as fast a i can. Please guide me what should i do

**Comment by tanaypratap** [comment]
Don't work too much. You need to give relaxed timelines. If the job forces you to do it, talk to your manager and make him understand that your relaxation and self learning is important as well. If things persist, I would advise you to find another job. Even if it is low paying, your per hour rate would be more and you should work towards increasing it even more. 
Say you work 80 hours .a week at $10 per hour, all you're making is $800
If you work for 50 hours a week at $20 per hour, you would be making $1000.
The key to getting rich is more money per hour and to do that you need time to learn.
