### ISSUE TITLE
Wanna take advice related to animation 

### ISSUE THREAD

**Issue by sarb001** [tanaypratap/ama#120]
Hey bro first of all it's really gd of u that u will help other students to get out of their problems related to coding etc. So my question is basically that i had started animation and want to peruse it as a career so can u  help me to figure out  what to start with to make animation films or in gaming and if u  know someone which has started any startup related to gaming provide me the contact if possible.  I'm waiting fr u r reply   and thks again

**Comment by tanaypratap** [comment]
Not my area of expertise. Find out someone who has made a career in this and ask for directions.
