### ISSUE TITLE
Which one is better, Angular or React??

### ISSUE THREAD

**Issue by MuttuKS** [tanaypratap/ama#123]

**Comment by prerana1821** [comment]
Hey @MuttuKS,
Tanay as published few newsletters & a podcast on this topic. I would suggest you to please go through it once.
Here's are the links: 
1. [choosing your stack](https://tanaypratap.substack.com/p/choosing-your-stack)
2. [how to choose the right framework](https://tanaypratap.substack.com/p/how-to-choose-the-right-framework)

Podcast:
1. [React vs Angular vs Svelte vs Flutter](https://open.spotify.com/episode/6AO5vHrJTXv9KF7lI981Z4?si=7pv1btLLTR6dfhWevua4nA&dl_branch=1)

If you have any questions feel free to comment on it.
Thanks :)
