### ISSUE TITLE
Please give an overview about how things exactly work in coding.

### ISSUE THREAD

**Issue by altazdaruwala** [tanaypratap/ama#13]
I am familiar with a few programming languages but I have no idea about how to use them to create PC softwares and apps. All i am taught is basic programmes with no GUI. Please cover this topic in one of your videos!

**Comment by prerana1821** [comment]
Hey @altazdaruwala,
I would suggest you to do levelZero which is free on youtube.
Here's the playlist: https://youtube.com/playlist?list=PLzvhQUIpvvuj5KPnyPyWsvgyzNkX_ACPA
If you have any questions feel free to comment on the videos.
Thanks :)
