### ISSUE TITLE
Big Data Analytics

### ISSUE THREAD

**Issue by HasnainMG** [tanaypratap/ama#131]
Good afternoon Sir,
I am currently studying Big Data Analytics.
I have done hadoop mapreduce and apache pig and currently learning Scala
Can you please guide me about the scope of Big Data Analytics.

**Comment by prakharrathi25** [comment]
Is Data Science overrated?

**Comment by HusainRegal** [comment]
Thank you sir....
When will you start Data Structures.

**Comment by HasnainMG** [comment]
Thank you sir....
