### ISSUE TITLE
Tell us about your journey and how you got into Microsoft, that would help others as well.

### ISSUE THREAD

**Issue by nidhimakdani** [tanaypratap/ama#14]
Hello sir, i am studying computer engineering, I want to know about your journey of engineering and how you get job in Microsoft so if possible give me the answer to archive my goals. Thank you ! @nidhimakdani

**Comment by tanaypratap** [comment]
Nidhi,

I am not a super coder like many out there who crack Microsoft's or Google's interview. What I am is a really good and passionate engineer. I make products and make them real good. This has come through thousands of hours of practice. 

However, sometimes I feel that if your aim is only to get into Microsoft then it's better to do DS n Algo and get in. I am not sure whether my way is better way and you should follow it coz I don't see a lot many people who got in here who are/were like me.
