### ISSUE TITLE
Is AI currently the best field to take 

### ISSUE THREAD

**Issue by srivatsan18** [tanaypratap/ama#145]

**Comment by knowsach** [comment]
watch "AI vs UI" on tanay pratap's YT channel.

**Comment by sushilburagute** [comment]
Here's your answer from Tanay's Youtube Channel!

[https://www.youtube.com/watch?v=Qz5_ccyusbg](url)
[https://www.youtube.com/watch?v=oZhXwCEBmmk](url)
