### ISSUE TITLE
Please Help #OfficePolitics

### ISSUE THREAD

**Issue by Rahul-Barick** [tanaypratap/ama#148]
I need help from you is how to avoid being criticized by office politics... Some people are just making the Office Enviornment very bad. Ignorance is the best way But if you love the technology stacks, Best Industry Coding conventions, Pr reviews & to be reviewed. I like everything But it's Irritating me & my self-confidence. Any Suggestions on how to tackle and Grow in the IT Organizations along with Your career. How is your life experience as such till now working with different Organizations. Did you face anything in your current Job life in Microsoft?

**Comment by tanaypratap** [comment]
can you provide some example of what you're facing? that would help me set context.

**Comment by rishitsaiya** [comment]
100+ Tactics for Office Politics is the best book I have read so far in this context. The link for the same is below.

https://archive.org/details/100tacticsforoff00hawl
