### ISSUE TITLE
Self doubt & overwhelming on new things

### ISSUE THREAD

**Issue by abdulsamadh** [tanaypratap/ama#158]
I'm an 18years old student from Brindavan University & i am pursuing B.Com first year.... 
I work in a company simultaneously, their people are so much talented, they're just 1-2 years elder than me but the way the communicate, exchange humours(I don't understand their humours but i just smile because it's embarrassing for me) 
Many times i shall have a good idea for execution but i can't pitch it or if i have to say anything i think 1000 times & make sentences in my mind and talk. And i am very enthusiastic in learning business, marketing strategies, sales & what not. May be that is the reason i started off early. This is my situation at work. Please align me to overcome this.

**Comment by tanaypratap** [comment]
Give it sometime. Things will improve. It's natural to feel stressed in a new environment with seniors around.

If you want a more detailed answer then please reopen this issue. I'll record a podcast/video to help.
