### ISSUE TITLE
Since I want to develop apps for android, can you teach Java as well?

### ISSUE THREAD

**Issue by shaheem-pp** [tanaypratap/ama#16]
Sir... I've already completed HTML and CSS.I saw you are teaching HTML in your YouTube channel

Sir now I want to move into Android App Development
Can you start a course on Java or Kotlin which eill help me and many more programming geeks in this world who want to step into Android App Development

**Comment by tanaypratap** [comment]
I won't be teaching Java or Kotlin in this course. This course is primarily focused on getting students a job, and the demand for web developers is at an all time high.

If you want to develop for mobiles, I would be covering how to do PWAs. You can watch [this video](https://www.youtube.com/watch?v=Qz5_ccyusbg&t=3s) for more context.
