### ISSUE TITLE
Expense Calculator App issue

### ISSUE THREAD

**Issue by SUSMOY97** [tanaypratap/ama#161]
Hey! I just completed vanilla JS course but the issue i am facing with the expense calculator is that suppose there are three items,whenever i am deleting one of the item it's working great but after deleting the third item when i am trying to delete the second item,the already deleted item is coming back into the list and creating the issue.Moreover the total amount is not getting reduced after deleting the item.

**Comment by knowsach** [comment]
please share your code

**Comment by prerana1821** [comment]
Hey @SUSMOY97,
This issue is not relevant to this repository. I would suggest you to go through the youtube video once again.
Thanks :)
