### ISSUE TITLE
Angular or React?

### ISSUE THREAD

**Issue by Aravindan07** [tanaypratap/ama#172]
Tanay which is better to learn angular or react

**Comment by sushilburagute** [comment]
Here's the link to the answer Tanay Sir wrote quite a time back...
[https://www.quora.com/Should-I-learn-React-or-Angular-if-I-am-already-an-android-developer](url)

And here's a video from his Youtube channel..
[https://www.youtube.com/watch?v=1bfvYKcDAUc](url)

Hope this answers your question!
