### ISSUE TITLE
Career Advice

### ISSUE THREAD

**Issue by RawHeatG** [tanaypratap/ama#178]
Hey Tanay, I just graduated and I'm currently placed in TCS and of course, I'm not going to achieve anything from such service-based companies.  How can get into good product based companies?

**Comment by RawHeatG** [comment]
How to get into a start-up. Should I go down on the full stack path or should focus on competitive programming.

**Comment by RawHeatG** [comment]
Currently, I'm in Chennai, and the plan I have right now is: Get shit done in full stack. Focus on DSA. Apply in good startups. Can you please give a comment on it, some things I should focus on or if I'm doing something wrong.

**Comment by RawHeatG** [comment]
Thank you so much man!, How you are helping us beginners as your younger brothers and sisters. RESPECT! Thanks, and it means a lot! Keep creating content!

**Comment by sbsoumavo5** [comment]
Sir, you had told , Georgia tech has partnered with udacity for online Ms and Illinois University has with coursera, does that mean people like me preparing for GATE to get into a tier 1 college in india for Mtech are just working hard and not smart?

**Comment by tanaypratap** [comment]
Close this thread and maybe open a different question number for this?

**Comment by sbsoumavo5** [comment]
Okay bhaiya!
