### ISSUE TITLE
Career advice

### ISSUE THREAD

**Issue by omkarsingad** [tanaypratap/ama#183]
Why is a certification of 3 months in some language is given more value than a 3 or 4 year college degree..

**Comment by tanaypratap** [comment]
Because companies want people who can get productive fast. They don't want to pay AND train you.
If you're trained, good for them.

**Comment by MuhammanUsmanAwan** [comment]
> Why is a certification of 3 months in some language is given more value than a 3 or 4 year college degree..

college degree is more of unwanted stuff like things of other fields are also taught or it is generic
while in certification of span 3 months or so; is more specific
