### ISSUE TITLE
Little query :-

### ISSUE THREAD

**Issue by prajvalrasik** [tanaypratap/ama#187]
Sir, what is your roadmap for 1st year BTech students as they don't have js in their 1st year course. They have all different subjects and just a bit if C programming (that too in 2nd semester). I mean we have a lot of maths, physics, chemistry to do in this year. Should we still continue with your course or should wait for some time? 

P.s.- I'm sorry if I sound stupid. Pardon 🙂

**Comment by tanaypratap** [comment]
Start coding in standard 6. After you have some grasp of English you should code. You're already late. Don't delay.
