### ISSUE TITLE
How to form a Student Developer Club in a non engineering college? 

### ISSUE THREAD

**Issue by shaheem-pp** [tanaypratap/ama#189]
My name is Shaheem.
About me, I'm first year BCA Student in Safi Institute of Advanced Studies under Calicut University, Kerala. I want to form a Google Developer Students Club in my College. Is it possible? Because its not an engineering institute or University? And how can I form a developer club in my college?

**Comment by sushilburagute** [comment]
First question is, Are enough students interested for it?
if no, get em on board!
if Yes, make a detailed plan. 
**Make a group of interested students and get a Faculty of your college on board** and it'll all work out!
Convince them by showing them your plan and how it'll be good for their career if they join you! 
Plan out the task you are going to do which will be for the betterment of others.

Don't know about opening a Google Developer Students Club but I do know about ACM and I'm a member on our college's team!
[https://www.acm.org/chapters/students/how-to-start-a-student-chapter](url) 
[https://blog.usejournal.com/initiate-developer-student-clubs-in-your-universities-e052caae7eb](url)
All the info about it is given here..


Hope this answers your Question!
