### ISSUE TITLE
How to get started with open source?

### ISSUE THREAD

**Issue by raghavddps2** [tanaypratap/ama#2]
Hi sir,

Please tell as to how a beginner can get started with open source ? 

Its very overwhelming to start contributing to big projects and so, please let us know as to how we as beginners can get started with it.

Thanks in advance.

**Comment by tanaypratap** [comment]
Update: See this-> https://teawithtanay.com/vue-js-and-getting-started-with-open-source-ft-rahul-kadyan-episode-4/

Let me be honest with you Raghav. I haven't done a lot of open source myself. I started very recently and I'm still figuring out stuff. I really want to answer this question well and bring value to it. Please give me some time to figure it out. I'll make a video about it.

**Comment by raghavddps2** [comment]
> Let me be honest with you Raghav. I haven't done a lot of open source myself. I started very recently and I'm still figuring out stuff. I really want to answer this question well and bring value to it. Please give me some time to figure it out. I'll make a video about it.



> Let me be honest with you Raghav. I haven't done a lot of open source myself. I started very recently and I'm still figuring out stuff. I really want to answer this question well and bring value to it. Please give me some time to figure it out. I'll make a video about it.

Okay no problem tanay, thanks for the reply, you are doing a great job guiding beginners like me. More power to you!

**Comment by raghavddps2** [comment]
Closing the issue as you answered the question on Instagram. Thanks a lot, looking forward to contribute to the repository you will create to help us get started with opensource. Can't wait to star it and see that contribution chart on my profile which just have commits and issues till now :P.
