### ISSUE TITLE
Can you suggest some resources to learn cloud computing?

### ISSUE THREAD

**Issue by gkanishk** [tanaypratap/ama#20]
Good evening sir,
I am a student from 2nd year currently pursuing BE CSE hons. in Cloud Computing from Chandigarh University.I am currently working on Android and I want to proceed with cloud computing in comming months as my semester is going to end. Can you guide me some resources how to learn work on cloud

**Comment by tanaypratap** [comment]
I'll look into this @gkanishk 
I think there are good free courses on Edx, Udacity and Coursera. However, I am not sure which one to recommend.

**Comment by gkanishk** [comment]
Ok, @tanaypratap thankyou.
If aiming for a cloud professional certification like cloud architect than which provider to opt with there are many AWS, Azure, GCloud and many.

**Comment by tanaypratap** [comment]
@gkanishk did you find the appropriate course?
