### ISSUE TITLE
How can one approach a company for an internship with basic-medium level of skill?

### ISSUE THREAD

**Issue by sushilburagute** [tanaypratap/ama#203]
Hey Tanay, Love your hacks! So I feel I'm ready to get myself into the industry and begin coding on some real products .... So any hacks to prove yourself to the interviewer? How would have you done it?
Thanks for your time! :)

**Comment by gkanishk** [comment]
Recently writen an article on that on linkedin

**Comment by sushilburagute** [comment]
### Thanks !!
