### ISSUE TITLE
Open Source and Competitive Programming while working.

### ISSUE THREAD

**Issue by RawHeatG** [tanaypratap/ama#207]
Hey Tanay!, Thanks for this AMAs. I just joined TCS and I want to contribute in open source and do a little bit of competitive programming as these will groom me up for a good product based company.
I'm very confused about how to get into contributing to Open-source.
Also any life hacks or tips on how to do competitive programming while working

**Comment by RawHeatG** [comment]
Yeah sure please do a podcast on it, give us all the info you have on it because I'm very confused how to start doing it.

**Comment by tanaypratap** [comment]
Please see this podcast for the same https://teawithtanay.com/vue-js-and-getting-started-with-open-source-ft-rahul-kadyan-episode-4/
