### ISSUE TITLE
Need help being a clg student

### ISSUE THREAD

**Issue by WhoAdarshPandya** [tanaypratap/ama#208]
Hi tanay ! First of all i want to thank you for teaching us react in such a great way. I want to ask you that , I'm in second year of college but all they have teach me is console based simple programs and arithmetic calculators. I want to learn how big applications work. Another problem is i leave the programming language when things get little bit tough. Hope you answer. Thank you

**Comment by tanaypratap** [comment]
Recorded in podcast. Will be released soon.
