### ISSUE TITLE
What types of projects can help in getting jobs at big tech companies?

### ISSUE THREAD

**Issue by dhruvam-zaveri** [tanaypratap/ama#21]
Sir i am a student in 1st year presuing CSE.Sir my dream is to get a job in a big tech company such as google, microsoft, uber, etc as a software developer.I was confused about what types of projects should i do during my college and build my portfolio for big tech companies.

**Comment by tanaypratap** [comment]
See this from here: https://youtu.be/EYr8k735axM?t=50

The kind of projects ( I mean web apps): 
1. A chat app
2. A realtime collaboration app
3. A social media app like Twitter/Facebook/Github
4. Some games
5. Apps related to network and security
6. Apps related to AI/ML


Make things to show that you have learned. That's the best way to get attention.

For other things checkout the video on [what to do in college actionable items:](https://www.youtube.com/watch?v=TSzgIOXxOZk&list=PLzvhQUIpvvujXvcaIthycttSLChcP_rF2&index=2)
