### ISSUE TITLE
From where i learn machine learning

### ISSUE THREAD

**Issue by husainhm** [tanaypratap/ama#211]
I recently learned python . now I want to learn machine learning. can you please suggest me from which website or application I have to learn machine learning ?
I one more thing
Can Career be Made in Machine Learning?

**Comment by sushilburagute** [comment]
Tanay has already talked Machine Learning on his youtube !

Ps(**Machine learning is a subset of AI**)

[https://www.youtube.com/watch?v=Qz5_ccyusbg](url)
[https://www.youtube.com/watch?v=oZhXwCEBmmk](url)
[https://www.youtube.com/watch?v=Lj3g1515osw](url)

If you really want to develop in Python, then look for Apps to build and replicate by yourself.

Hope this answers your Question!
