### ISSUE TITLE
Regarding SAP GRC, Career advice😀

### ISSUE THREAD

**Issue by Koushith** [tanaypratap/ama#214]
Hello Sir, i did my BCA from tire 3 college.. I was not getting any interview calls, struggling to get an call letter for interview...

After reaching lots of people through Linkedin i got referral from one of the EY (Big4) employee ..  Got placed there.. Its for SAP GRC profile... I dont know much about SAP GRC, im interested in Development(im not a pro, still working on it)

Does SAP GRC has anything to do with development? Whats the scope of SAP GRC(googled it it has nice feedbacks)

If i start with SAP GRC can i switch in future??

(Do check my Github profile, any feedback suggestions are welcome😀😗)

Thank you😊😊

**Comment by tanaypratap** [comment]
I don't know. You need to do your own homework kid.
