### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bhaveshkumar05** [tanaypratap/ama#215]
Sir, i am very passionate about coding but I'm doing BCA by distance education so i think that i don't have any future because I am not even a regular college going student can you give me some tips can i get job in a good company in the future what can i do and sir i was a biology student so didn't have maths in 11th and 12th so i am very weak in maths so can you tell me the maths topics used in web development (front end and back end both) so that i can learn it.
I'm passionate about web development and android development  (maths according to these careers)

Q2. How important are DSA to get into startups and how we can learn it for companies like Google, Microsoft, etc.

Thank you so much

**Comment by sushilburagute** [comment]
The main thing is, build your basics first! There's enough help on youtube to build your logic.

Coming to the Maths, nothing complex is required. Basic Algebra and logical statements are commonly used. (See the link attached)
[https://www.freecodecamp.org/forum/t/should-i-be-good-at-math-to-be-a-web-developer/109535](url)
[http://jumpstartlab.com/news/archives/2013/04/08/wdm-101-web-development-math-101](url)

So maths is not not the issue!

DSA is super important as companies always tend to look out for it. Assuming you're starting out, have immense knowledge in this topic. 
[https://www.tutorialspoint.com/data_structures_algorithms/index.htm](url)
Here's a link to get you started.
Be patient, coding is like working out at a gym. You get better as time progresses!
