### ISSUE TITLE
MS online vs Mtech from top colleges in india, and GATE advantages

### ISSUE THREAD

**Issue by sbsoumavo5** [tanaypratap/ama#219]
Sir, you had told , Georgia tech has partnered with udacity for online Ms and Illinois University has with coursera, does that mean people like me preparing for GATE to get into a tier 1 college in india for Mtech are just working hard and not smart?

**Comment by prerana1821** [comment]
Hey @sbsoumavo5,
Tanay as made recently made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/JbGjZk_EQpg
If you have more questions on this topic feel free to comment on the video.
Thanks :)
