### ISSUE TITLE
How important it is to make notes while learning something?

### ISSUE THREAD

**Issue by Shshankm597** [tanaypratap/ama#225]
My question is how important it is to make notes while learning something? Is it good to just read/understand things and not to right it down somewhere or notes should be created properly?

**Comment by sonalisikarwar** [comment]
Making notes is necessary due to following reasons
1.It helps in revising at the exam time
2.When ,we read something for exam. We have to write it  in own language
for memorizing.

Scientific reason behind note making .

**Comment by Shshankm597** [comment]
Thanks.
