### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bhaveshkumar05** [tanaypratap/ama#226]
Hello, Sir, i am very passionate about coding but I'm doing BCA by distance education so i think that i don't have any future because I am not even a regular college going student can you give me some tips can i get job in a good company in the future what can i do and sir i was a biology student so didn't have maths in 11th and 12th so i am very weak in maths so can you tell me the maths topics used in web development (front end and back end both) so that i can learn it.
I'm passionate about web development and android development (maths according to these careers)

**Comment by sonalisikarwar** [comment]
If you are passionate about coding web developement continue learning. It doesn't matter you are from which background or you have maths in  your course or not.

**Comment by tanaypratap** [comment]
@Bhaveshkumar05 first thing is to communicate well. Read your question. It looks like you're having a heart attack and these are your last words. All jumbled up. Please ask your question in a well formed manner. Update the issue with a title. Just 'help' doesn't cut it. 
Everyone is here for help only right?
