### ISSUE TITLE
I have made a portfolio. It's scrolling in desktop(every browser) properly but when i am opening it in my mobile phone browsers, it's not scrolling properly. Except scrolling there is two more issues - experience and resume is not loading and opening respectively.

### ISSUE THREAD

**Issue by h0m3brew** [tanaypratap/ama#227]
https://glob4lh3ll.github.io/rohit_rathaur.github.io/
it is the link of my portfolio. And the repo link is
https://glob4lh3ll.github.io/

**Comment by tanaypratap** [comment]
Ask these questions in fb group. bit.ly/lcf-fb. 
or on stackoverflow. 
A major part of programming is to understand where to ask what questions so that you can get proper answers. Learn this. It will help you.
