### ISSUE TITLE
Mathematics and software engineering

### ISSUE THREAD

**Issue by shaheem-pp** [tanaypratap/ama#228]
Sir, I'm a first-year BCA student. Today in my calculus class, the teacher told that differentiation and integration are applied in software development. That was a shock for me.... Where does these things are applied in programming?
Actually most of the beginners have the same doubt, where did the mathematics used in Programming
Expecting your reply

**Comment by sonalisikarwar** [comment]
Maths is used in parallel computing,artificial intelligence  and for nuclear tests.When ,we are doing bca for learning about basics of computer and in Mca in details. If you want to do masters maths needed and for complex problems maths needed. 
But Tanay sir is teaching full stack stack. You can do it easy things like web designing and more by watching videos of Tanaypratap videos on YouTube. But degree is also necessary for good job.For degree you have to pass all subjects with good marks.

**Comment by tanaypratap** [comment]
AI, Quantum Computing etc are pure Maths. Maths and Physics is how this world works. If you want to create something new you need to understand these concepts.
On a day to day level, it's not needed.
