### ISSUE TITLE
Why should I learn JavaScript?

### ISSUE THREAD

**Issue by gkanishk** [tanaypratap/ama#23]
Greetings sir,
I am in second year and currently working on Java . I decided to work with Java and python throughout as I am learning Android Development.Now you are deviating us learning JavaScript why so.
Can you tell which language to work with and why.

**Comment by gkanishk** [comment]
What are the fields JavaScript is used for is it only used for web dev or lot more.What if I don't want to go with Web Development.

**Comment by tanaypratap** [comment]
If you are good with Java and Python, why do you want to shift to Javascript? @gkanishk

**Comment by gkanishk** [comment]
I am learning Android Dev using Android Studio (Java) intermediate level and after going through your content web impressed me (kind of deviated me 😆) so now I want to skill in both Android and web dev so I want to shift to JavaScript.

**Comment by tanaypratap** [comment]
I would say go through the highlights and videos I have posted on Instagram. I keep talking about why JS is the way to go. Even recently, in an AMA I talked about it. There's huge demand for Javascript and thus, I am teaching or pushing people to do it.
