### ISSUE TITLE
Unable to publish website using netfily.

### ISSUE THREAD

**Issue by adityasinghbaghel** [tanaypratap/ama#230]
Hey! Tanay I watched your youtube videos and tried to publish my website using netfily site was getting published but in webpage not found . I searched on youtube and googled but did'nt get that . I am using windows and on the web i was getting answers for mac . Pls help to solve my problem. (https://github.com/adityasinghbaghel/HACK/blob/master/Netfily/business.html) and
(https://github.com/adityasinghbaghel/HACK/blob/master/Netfily/style.css)

**Comment by khusharth** [comment]
Hey Aditya. I checked your GitHub repository and saw you named your HTML file as business.html. Change that to index.html and your web page should work.

**Comment by adityasinghbaghel** [comment]
Thank u khusharth . It worked 🤗 but why it was not working with business.html. Do you have any idea.

**Comment by khusharth** [comment]
Glad to know that :). Index.html is the default name used for the homepage of websites. So whenever someone will type the name of your website (eg www.aditya.com) the web-server (here netlify) will try to find index.html in your folder and return it to the user. 
For more details you can read here https://www.lifewire.com/index-html-page-3466505

**Comment by tanaypratap** [comment]
Thanks for being the hero Khusharth! Helping out here! Appreciate it.
