### ISSUE TITLE
Carrier Advice for someone with 8 years of experiance in service company

### ISSUE THREAD

**Issue by mohan-murali** [tanaypratap/ama#246]
I did my engineering in mechanical from a not so special college and got placed in a service company. At first, I was not interested in the work so I never bothered learning or being better. But I would put on the hours to complete the work given to me. But soon I realized that I was getting more and more irrelevant as the day goes by. My life was getting worse and worse and even my salary was pretty low. But by the time I realized this I was already 5 years into the company. I started learning dotnet soon and got a job in another service company but this time as a developer. Here I had more interaction with my client developers on-site and I realized that they are a lot better then I am. While working here I also got to pick-up on ReactJS and javascript which has a very big and vibrant community, unlike dotnet. Now I am reaching 8 years of experience. I don't know what to do next. Usually, people in service companies start moving to people management at this time. But I am neither good nor interested in that. I realize I have made mistakes in the past and now I am trying to correct them. But I am not sure what to do as most companies are not even hiring for people like me. Can you please give some help and guidance on how to proceed with my life and my mistakes.

**Comment by tanaypratap** [comment]
I don't have any idea on what suggestion to give. You're late to the party.
Only thing I can suggest is that you learn web developement. Develop some web apps and work with few small scale start-ups which are ready to give you a break.

Start-ups look for developers desperately.
