### ISSUE TITLE
How should a data warehouse developer leverage one's profile??!!!

### ISSUE THREAD

**Issue by Saptarshee** [tanaypratap/ama#252]
I have been working as a Data warehouse developer (5+ yrs in ETL development and reporting) . I hardly have any strong knowledge in any of the coding language as I couldn't grab any chance for real time implementations. It's high time I want to leverage my profile. I tried learning with help of online resources few times and built small apps (using python, JS etc) but couldn't go further. It would be really helpful, if you share/guide/comment anything on how should I start and which stream should I pick. 

I was planning to start reading some basic algorithm/DS learning and python problem solving books. I would appreciate any suggestions on the same. :)

**Comment by tanaypratap** [comment]
I don't know about these fields in depth.
