### ISSUE TITLE
Data structure 

### ISSUE THREAD

**Issue by AdarshJha1** [tanaypratap/ama#258]
Good evening sir,
Right now I am learning DS & Algo.
I have completed Array, Strings, Divide and conquer, but I do not solve too much question
what should be the good approach? Firstly, read all the topics and then start practicing or read one topic and solve question-related to that?
sir, please guide me

**Comment by sphoorthigaddam** [comment]
Hi Adarsh,
I would like to share something which helped me. 
Learn a topic and then start solving problems related to that. It will help you understand the concepts clearly. Reading everything and then practicing will not take us anywhere, all we need to do for DS and Algo is practice. 
Also, it is not just about solving questions we need to understand the concept of the question and should be able to apply it to a similar problem. 

@tanaypratap not sure if someone apart from you can answer the issues. But, I thought I could help here. Would love to listen your answer too.

**Comment by tanaypratap** [comment]
See the answer to this one in detail.

https://anchor.fm/tanaypratap/episodes/Learning-strategies-for-Data-Structures-and-Algorithms-ed6u9q
