### ISSUE TITLE
Error in Linkedin profile linking

### ISSUE THREAD

**Issue by reachtokish** [tanaypratap/ama#260]
I just wanted to let you know that I found there is an error of your Linkedin profile linking in learncodingfree.org. There is a section called `your instructor`, once someone clicks on that it redirects to an invalid Linkedin URL. It supposed to redirect to your profile I guess. Not sure it's an issue or what but lots of people visit that website that's why wanted to let you know.

Clicking on this >
![image](https://user-images.githubusercontent.com/10685261/79696614-65f02480-829b-11ea-8d41-ba761ed72b30.png)

Redirects to >
![image](https://user-images.githubusercontent.com/10685261/79696627-8e781e80-829b-11ea-94ac-ad3024248f58.png)

Thanks,
Kishore

**Comment by tanaypratap** [comment]
Thanks for reporting the error. I fixed it. Kind of you!

./Tanay
I am a mentor for college grads. if you or someone you know wants to learn
JS, or get a job. Check out learncodingfree.org and jobChallenge.dev

**Comment by reachtokish** [comment]
No prob :)
