### ISSUE TITLE
How to get  JOB in microsoft

### ISSUE THREAD

**Issue by kuldeepvatsal** [tanaypratap/ama#262]
Hi,
Tanay,
i am  Kuldeep Singh i have total 8 year experience in dot net console application  and i am learning Azure . please can guide me how i can get job in Microsoft corporation

Thanks
Kuldeep

**Comment by tanaypratap** [comment]
I'm not the right person for this. I'm mostly into programming. Also, I
don't give MS specific advice.

./Tanay
I am a mentor for college grads. if you or someone you know wants to learn
JS, or get a job. Check out learncodingfree.org and jobChallenge.dev
