### ISSUE TITLE
If I am not good at coding should I go for cloud computing i.e. AWS or Azure certification?

### ISSUE THREAD

**Issue by shivambhatia5432** [tanaypratap/ama#28]
I am currently in first year of college pursuing B.Tech.
My mathematics is not good and I am average in coding(C,C++).
Never made a project ever.
I am thinking of pursuing career in cloud computing.
So my question is,
In my holidays should I prepare for Aws certification or improve my coding skills like my other friends are doing.
I would love to be guided by you, I know you are a little busy for your free course all the best for that.
Anyhow whatever you suggest I will definitely take your course in my holidays.

**Comment by tanaypratap** [comment]
When you're in college, that too in first year, don't give up so easily. Coding would feel very easy if you start doing it daily. 
As for the certifications, I don't think they will be useful a lot in 4-5 years in your career. You should know about cloud, definitely but should be good at programming if you want to really make a career in computer science.

**Comment by tanaypratap** [comment]
When you're in college, that too in first year, don't give up so easily. Coding would feel very easy if you start doing it daily. 
As for the certifications, I don't think they will be useful a lot in 4-5 years in your career. You should know about cloud, definitely but should be good at programming if you want to really make a career in computer science.
