### ISSUE TITLE
Is Webflow disrupting the field of front-end handy developers ?

### ISSUE THREAD

**Issue by sujayxaradhya** [tanaypratap/ama#282]
Nowadays, why some developers are migrating to Webflow ?
Is it right to migrate to Webflow tool ?
What's your opinion on this ??

**Comment by tanaypratap** [comment]
Webflow WordPress etc has always been there.
Developing website is a low level job and automation will eat it.

However, if you see more and more companies are hiring for web developers. JS is the most in demand skill. Are companies fool?

Understand the difference between an app and a marketing page or a blog. 

You can't make a slack or a Google doc in webflow.

More points to be discussed around 
How web is the next frontier
Desktop apps are moving to web
Mobile apps are moving to web

Write once run everywhere.

Testing and automation is getting done in NodeJS.

**Comment by tanaypratap** [comment]
Check out an entire podcast discussing this in detail [here](https://open.spotify.com/episode/3dcnvvmEG8oKbmjwwmBqaU?si=0jMlqdkRQQmjiv_pxiQpng)
