### ISSUE TITLE
Tips to improve English for engineers and cracking interviews

### ISSUE THREAD

**Issue by amargulaganji** [tanaypratap/ama#31]
Tanay 
Is english communication skill matters?
I am ok in english but not fast and fluent..
I m asking this question bcz i was rejected by 2 companys HR interview because of my english communication....
I m good in coding part 
I can clear coding tests and technical interview by the companys 
But not clearing HR

Bcz of this i m feeling myself down and shame ... Going depression day by day
Now i lost the hope of getting job

**Comment by prathamponnana** [comment]
+1

**Comment by spiderap339** [comment]
+1
