### ISSUE TITLE
Question for podcast.

### ISSUE THREAD

**Issue by nitintushir0048** [tanaypratap/ama#310]
1). Beginners guide to research paper. Should we start writing research papers in college. how beginners can start with writing research paper. Guide to conferences and publications.

2). How to build a strong online presence.(i write a blog :- https://tushirnitin.wordpress.com/) .what different strategies can be used for better reach.

3). Guide to stackoverflow.

4). shifting from non-technical to technical.

5). what about training institute (they charges 30,000 for 3 months training) . does it bring any value ?

**Comment by mitanshukr** [comment]
6). Work-Life balance in IT industry: A guide to freshers.

**Comment by tanaypratap** [comment]
Put questions as separate issues.
