### ISSUE TITLE
Career Choice 2020: Java or JS

### ISSUE THREAD

**Issue by mitanshukr** [tanaypratap/ama#317]
Hello sir, Good Morning...
I've learned (and still learning) java in past months. Now should I make progress in java itself and make projects based on it(for eg; java desktop app), or should I start learning new technologies (for eg; JS, React, nodeJS) and make projects on these trending technologies?

Which option will have higher growth in the coming days of the industry?

P.s: I'm 2020 graduate from ec branch and planning my career in IT industry.

Thank you!

**Comment by tanaypratap** [comment]
Have answered this multiple times. See my video and Instagram posts
