### ISSUE TITLE
Overcome side effects of being odd one out/lonely during interview preparation/reading good books/yoga

### ISSUE THREAD

**Issue by shubham1202** [tanaypratap/ama#320]
I am a working professional, in a small company for past 2 years. Want to get into the big league companies. The problem I face is that I prepare consistently for like 7-10 days and then I lay back for undefined number of days, and this cycle is repeated. What I feel the reason is that I am not surrounded by the people/culture who are interested in learning things, no big career targets that helps keeping motivated. Not only interview preparation, it's true for the good things I try to adopt in my life like doing yoga or reading self help books. So how to overcome this and be consistent, as I do not have the option to get along with entirely a new set of peers. And the journey for interview preparation will be long for me, like 8- 10 months.

**Comment by tanaypratap** [comment]
Shubham this will be answered in the book on productivity. Please stay tuned for that.

Idea: hangout with people online.
