### ISSUE TITLE
About MERN stack and DENO

### ISSUE THREAD

**Issue by VishnuPrasad1998** [tanaypratap/ama#321]
Sir, 
I am a great fan of yours and I think I completed your YouTube videos. I was having a question unfortunately I was not able to get the answer on the live session because of the crowded chat. My doubt is whether I should pursue MERN stack ? What will the effect of DENO over express ? Also to become a full stack developer which is the a better option to go with react front end Golang Rest API or Express.js ?

**Comment by tanaypratap** [comment]
This will be answered in Developer Roadmap Talk coming soon on YouTube.

**Comment by VishnuPrasad1998** [comment]
Thank you Sir
