### ISSUE TITLE
What should be dream position of Designer & Developer and what are skills of both side one can learn which complement each other?

### ISSUE THREAD

**Issue by manjots1607** [tanaypratap/ama#324]
Hi Tanay, 
  I am manjot, I have knowledge of Graphic Designing in photoshop (poster design) and MERN Stack, and I also had good experience in both skills, But I mainly focus on development as I my believe is that I can either work as designer or developer, and recently I watched your video on building tech portfolio and I had thought in my mind that I should put designing in my portfolio, but I am unable to figure out where to put designing (safe stock or large cap ) and what type of skill should I learn in designing that would compliment development.

**Comment by tanaypratap** [comment]
I asked @siddharthkp to answer this. He has put his thoughts in a video here. 

https://twitter.com/siddharthkp/status/1273918000534601729?s=19

**Comment by manjots1607** [comment]
Thanks sir for considering this, & I watched the video and found that I should try for one side (development) and then move towards decisions related to other side (design).
