### ISSUE TITLE
How to make great/big startups if you don't know how to build/code complex apps?

### ISSUE THREAD

**Issue by sumanthyedoti** [tanaypratap/ama#327]

**Comment by sumanthyedoti** [comment]
Hi @tanaypratap 
Sorry about writing everything in the header, if that is not fine. Awaiting your views and guidance

**Comment by tanaypratap** [comment]
You either learn to build yourselves or you get money to hire.

**Comment by darshanr27** [comment]
+1

**Comment by JatinRanka** [comment]
+1
