### ISSUE TITLE
Should people get a Master's Degree even if they want to do Software Development ?

### ISSUE THREAD

**Issue by purvasheth** [tanaypratap/ama#331]
Should someone who loves coding and **does not want to do ML/AI** go for a Masters's Degree abroad?

I know it's not needed but does it help? 
Especially if you are willing to take a loan and manage to get into a good university. (Ivy League)

Will job prospects in India get better once you finish masters and get some work experience abroad?
Or would they be similar if you work hard in India during that time instead?

**Comment by amanpandey04** [comment]
+1

**Comment by kolharsam** [comment]
+1

**Comment by shubhams711** [comment]
+1

**Comment by mvedang** [comment]
+1

**Comment by divyajyotiuk** [comment]
+1

**Comment by Jaynil1611** [comment]
Even if someone wants to do ML/AI as future prospect after getting some work experience and understanding the industry
Is a Master's Degree still required for that?

**Comment by tanaypratap** [comment]
Thank you for all the upvotes. 
Here's the answer. 

https://anchor.fm/tanaypratap/episodes/Do-we-need-to-do-Masters-to-become-a-great-programmer-efmba9/a-a2gudq7

**Comment by Jaynil1611** [comment]
#### Thank You so much for the detailed answer!
