### ISSUE TITLE
Can a student from tier 3 college get a job in tier 1 company as a fresher? If yes how can a student prepare for it and how could he/she get it? 

### ISSUE THREAD

**Issue by darshanr27** [tanaypratap/ama#333]

**Comment by imabp** [comment]
@darshanr18, may be sir is on some other important work in his life. So he couldn't find time to  answer. But  I got a video for you by Rachit Jain who says what would he do, if he was from tier 3 college.
Here is the link : https://www.youtube.com/watch?v=rUXGh95pqBo
It may help you
