### ISSUE TITLE
Will there be another iteration of the Tanay Pratap Job Challenge?

### ISSUE THREAD

**Issue by raniyer** [tanaypratap/ama#340]
Hi, I'm a second year student, going to my third year this semester, I wanted to take part in the challenge to learn more about react, but i noticed that the challenge is coming to an end this month, will there be another iteration of this challenge any time soon?

**Comment by prerana1821** [comment]
Hey @raniyer,
Job Challenge has now turned to roc8.careers.
Please visit the website to know more 
[roc8.careers](https://www.roc8.careers/)
