### ISSUE TITLE
does academics 60% matters ?

### ISSUE THREAD

**Issue by i-am-shashank** [tanaypratap/ama#346]
i am pursuing a BCA course from which i am quite happy, i love tech i love code i score good in every coding exam(semester ones)
i code at Hackerrank, codechief, but the problem is i was not good at my school studies which led to 59.8 % in my 12th which is just 1 marks less than 60% ,.......so how does this will affect my job, and how can i overcome this.

**Comment by prerana1821** [comment]
Hey @this-is-shashank-mishra,
Tanay as made recently made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/VpXDUTPzrdg
If you have more questions on this topic feel free to comment on the video.
Thanks :)
