### ISSUE TITLE
How to choose which direction to go in : MERN Stack V/S. Machine learning and Deep Learning

### ISSUE THREAD

**Issue by sahilBhola98** [tanaypratap/ama#352]
One is having already emerged and used by many companies, one is where i can research, evolve, explore. How to choose in term of opportunities and will stay in good quality race  with that technology for long

**Comment by prerana1821** [comment]
Hey @sahilgenius1,
Tanay as made made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/oZhXwCEBmmk
If you have more questions on this topic feel free to comment on the video.
Thanks :)
