### ISSUE TITLE
Is CSS tough or easy to work with- Answered by Tanay Sir

### ISSUE THREAD

**Issue by JLohani** [tanaypratap/ama#353]

**Comment by JLohani** [comment]
Answered by Tanay Sir on Telegram-

CSS is not easy. It's tough because of many reasons.
1. It's verbose. You need to know a lot of keywords to make it work.
2. It's declarative. Which means your normal programming logic doesn't work.
3. There's cascade which you need to understand. A lot of people don't do CSS well because they don't understand cascade well. 
4. There are tons of other concepts like box sizing, position, media query etc. which you need to understand. 

I have read the book CSS the definitive guide and it helped a lot TBH. You can check it out if you're serious about being good in CSS. 

But the struggle goes on, as we as web devs practice CSS less.

**Comment by cmcodes1** [comment]
@JLohani You should close this issue after the answer has been posted.
