### ISSUE TITLE
Guidance on how to start writing blogs

### ISSUE THREAD

**Issue by kaustav1810** [tanaypratap/ama#355]
I was wondering how to write blogs on my projects,learnings to highlight my presence on networking platforms like LinkedIn as you have already mentioned that it's very important to make your mark.

P.S. I have never ever written a blog before and thus looking for some help.

**Comment by prerana1821** [comment]
Hey @kaustav1810,
Tanay as recently published a newsletter on this topic. I would suggest you to please go through it once.
Here's the link: [Alexa! Suggest a blog topic](https://tanaypratap.substack.com/p/alexa-suggest-a-blog-topic)
If you have any questions feel free to comment on it.
Thanks :)
