### ISSUE TITLE
Open Source Contributions Importance

### ISSUE THREAD

**Issue by rohitb1023** [tanaypratap/ama#36]
Do you think open source development can help in career or getting a job ? (insta :-rohitb1023)

**Comment by tanaypratap** [comment]
Yes Rohit, it is incredibly helpful. 

Checkout this [video](https://www.youtube.com/watch?v=TSzgIOXxOZk&list=PLzvhQUIpvvujXvcaIthycttSLChcP_rF2&index=2) where I talk about how it helps.
