### ISSUE TITLE
From placement perspective, should I bet on something new like Flutter or do competitive coding? 

### ISSUE THREAD

**Issue by gauravmishra-17** [tanaypratap/ama#37]
Seeing around, I plan on having good ratings on various competitive sites, that will help me landing a good and quick job after my fourth year. The thing is I belong to a middle class family and my father is a government employee. Coding is my passion, but it is also a need. 
If flutter cannot help me in landing a good job, then i suppose i should focus on competitive coding. But please "discuss about the scope flutter has to offer". This is my main concern.

**Comment by tanaypratap** [comment]
Flutter is good and looks promising. Yes!

However, as a general piece of advice, I would always say not to bet on a new piece of tech. For your question, I would say first get placements. In India to get placements, you need to be good at DS & Algo, so concentrate on that. Once in job, keep a tab on Flutter, it will take some time for Flutter to grow. When it grows, then jump to it.
