### ISSUE TITLE
Govt. Jobs vs private IT jobs

### ISSUE THREAD

**Issue by thesparkvision** [tanaypratap/ama#370]
Hi sir,
Recently I got to hear from somebody that in private sector, employees are harshly treated. Lots of work has to be done and managers abuses employees day in and day out. Also there is not job security. So one should try for government jobs. Also that people who don't want to live with their family want to go for private IT jobs so they can stay far from family and live their life. I want to know your perspective on this and is it true that IT jobs are very harsh or is it just a myth being supplied because of some exceptions and is just folklore ?

**Comment by prerana1821** [comment]
Hey @thesparkvision,
Tanay as recently published a newsletter on this topic. I would suggest you to please go through it once. 
Here's the link: https://tanaypratap.substack.com/p/public-or-private
If you have any questions feel free to comment on it.
Thanks :)
