### ISSUE TITLE
Projects for elevate labs 

### ISSUE THREAD

**Issue by anshuldaksh2016** [tanaypratap/ama#375]
Hey ! I just wanted to know when we say good projects what does "good projects " holds . Can u please mention atleast 7-8 so that I can pick 5 of those and start making them.

Thanks 
Anshul Daksh

**Comment by prerana1821** [comment]
Hey @anshuldaksh2016,
Tanay as made recently made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/Vrwltd0y7p0
If you have more questions on this topic feel free to comment on the video.
Also, now elevate labs is renamed to [roc8.careers](https://www.roc8.careers/).
