### ISSUE TITLE
Career Path

### ISSUE THREAD

**Issue by anushkagarg5653** [tanaypratap/ama#379]
How to choose between two different tech fields. I am currently learning Machine learning and in my first year I was learning web development. How to choose which one to Conti. I enjoy learning both and do I really need to choose ?

**Comment by prerana1821** [comment]
Hey @anushkagarg5653,
Tanay as made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/oZhXwCEBmmk
If you have more questions on this topic feel free to comment on the video.
Thanks :)
