### ISSUE TITLE
Understanding Impact of frontend developer and how to motivate them with sense of accomplishment

### ISSUE THREAD

**Issue by gauzpan** [tanaypratap/ama#384]
Hi Tanay, 
I read your article - "web dev is a win", and it highlights pretty well what a web developer does as a whole. Recently, I am facing trouble explaining to new web developers the impact that web dev makes in the company product. We  are part of a product team building a web app for cloud computing,however one intern asked me after working for an year that since we have a  B2B product, and its tech-heavy, the major logic part, orchestration of the features and the design of the logic in the feature is kept in the hands of a backend developer. According to him, since in frontend the tools are already laid out by senior folks, he feels, he is not creating much impact, creating up the UI seeing the VDs and using existing components and services at his disposal. Rather, he feels the backend developer is involved with handling a large amount of data, writing the algo for the feature, so now he wants to make a switch for the same reason. So my question is how do we motivate or retain developers in the frontend role giving them more opportunities that give them a sense of accomplishment of creating an impact for the customer.  

I will be grateful, if you can answer this, or dedicate a blog post for the same, on how in B2B, web developers can create a meaningful impact related to revenue generation.

Thanks

**Comment by shubhamkhuntia** [comment]
Ha there been an answer to this? If yes I would like to know
Also can you share the link to that article.

**Comment by gauzpan** [comment]
Unfortunately, I don't have a link for the article now. Secondly, there is no one answer to this, it depends on how the team is showing respect to the frontend work and appreciating the efforts put forth by the team. Also, in between the individual needs to be shown value he adds to the product/software they are building by quantifying it with something like revenue, hours saved, etc. Appreciation is the key. Third, full stack dev should be encouraged more rather than just frontend dev, with engineers in the team should be shuffled in between sprints. Lastly, it is hard to find motivated frontend only engineers, initially you can get few young folks to work on it, however over a period of time, the motivation fades away, if there is no innovation.
