### ISSUE TITLE
What's your opinion on Flutter?

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/ama#39]
Related  to #37

**Comment by gauravmishra-17** [comment]
Bhaiya given that a single code base for android and iOS works and moreover now since web apps can also be made using flutter, i probably think there is going to be a boom in coming years in flutter development. And also thanks for answering my issue. Means a lot!

**Comment by HackrHIVE** [comment]
According to me,
Flutter is going to be very important in upcoming years as Google is currently working on their new Operating System _**Fuchsia**_ which is going to be compatible with any device and they will be interconnected and guess what, Flutter will be used to develop applications for Fuchsia.
Other than this, Flutter is currently being used for developing applications for Android and iOS with 1 codebase.
This prevents users from maintaining 2 codebases for different platforms.
Thanks!

==UPDATE==
And now they are working on Flutter for Web and Windows support which will help developers to develop web applications and windows applications also with one codebase.

**Comment by tanaypratap** [comment]
I recorded my opinions on this just now. Will be released on IGTV and Youtube. Links are in README.

**Comment by tanaypratap** [comment]
Released on IGTV. Please check.
