### ISSUE TITLE
Is there a bias against tattoos in software engineering field?

### ISSUE THREAD

**Issue by priyadarshini-26** [tanaypratap/ama#40]
My instagram user id : ay.irp 
I heard my friends and seniors telling me that u can't put tottoos when u r in sofware field and wen u r attending a interview u might not be selected evev bcoz of that tattoo .
Is that true?

**Comment by tanaypratap** [comment]
This is a great question. I'll take this up in video. This is something which needs to be discussed more openly and would benefit a lot of people. 
Watch the Youtube space for this question.

**Comment by priyadarshini-26** [comment]
Okay thank you bhaiya!  💯

**Comment by tanaypratap** [comment]
https://www.instagram.com/p/ByF2a9MlDxW/ 
Answered here.
