### ISSUE TITLE
What framework would you recommend to learn for development?

### ISSUE THREAD

**Issue by raje00** [tanaypratap/ama#45]
Is it required to learn any specific framework for development and if so then what will you recommend to learn? And i also know the benefits of it.

**Comment by tanaypratap** [comment]
React is the most promising library to learn for Web development currently. I would bet on it.
If you are a beginner, I would recommend going for the MERN stack.
There's a simple benefit there, the entire stack is in Javascript so, it's very easy to learn and make apss and there's enough demand around it.
