### ISSUE TITLE
When is the course coming and how long it will take to get completed . !! ( also read description).

### ISSUE THREAD

**Issue by albaabhusain** [tanaypratap/ama#64]
what is the duration of the course i mean ..when will i be able to finally start freelance or do something for entrepreneurship.

**Comment by prerana1821** [comment]
Hey @albaabhusain,
Tanay as published a  series of newsletter on this topic. I would suggest you to please go through it once.
Here's are the link: 
1. https://tanaypratap.substack.com/p/freelancing-series-i-the-good-parts
2. https://tanaypratap.substack.com/p/freelance-series-ii-what-could-go-wrong
3. https://tanaypratap.substack.com/p/freelancing-3-avoiding-the-pitfalls

If you have any questions feel free to comment on it.
Thanks :)
