### ISSUE TITLE
Is B.Tech in Computer Science Important?

### ISSUE THREAD

**Issue by aarryaannnn** [tanaypratap/ama#67]
is it important to do b tech in computer science to become a developer? will i be able to get a job in machine learning ? if i not do b tech in computer science

**Comment by tanaypratap** [comment]
Just recorded the answer. The video will be released on IGTV and Youtube.

**Comment by prerana1821** [comment]
Hey @aarryaannnn,
Tanay as made recently made a youtube video on this topic. I would suggest you to please go through it once.
Here's the video: https://youtu.be/JbGjZk_EQpg
If you have more questions on this topic feel free to comment on the video.
Thanks :)
