### ISSUE TITLE
Confused!!!!!!!!

### ISSUE THREAD

**Issue by vijay011** [tanaypratap/ama#70]
hello sir, I am just 16 years old I want to start coding but I am confused that from where to start and what to learn pls suggest me.
thank you

**Comment by gkanishk** [comment]
Try to solve basic programming question pick a language first and try to improve and make logic strong. You can solve questions on HackerEarth, Hackerrank first then master through code chefs questions and challenges. Accordingly, learn web taught by @tanaypratap sir. These things would be good to start with.

**Comment by gaurishxjfk** [comment]
I started by learning basics of c and java. then did bit of data stuctures.
After that i learnt HTML and CSS.
and currently learning vanilla js .
if u learn any one of basic language(c or java) its easy to learn other languages as concepts and analogies are same just syntax chnages.
