### ISSUE TITLE
Career guidance

### ISSUE THREAD

**Issue by mdsaifsid** [tanaypratap/ama#73]
Hi brother love your teaching stuff and it touches my heart i am confused about freelance programming what is it and does it have a scope of bright future ahead and one thing is that i love learning so i want a career so that I can learn

**Comment by tanaypratap** [comment]
For freelance work. Start learning web development first. Then make a
portfolio with few projects. Then go find work on Internet.

Pyjama Profit is a book which talks about it in detail.
