### ISSUE TITLE
Hackathons

### ISSUE THREAD

**Issue by Manish-M2018** [tanaypratap/ama#76]
I had seen your video in which you have told that certificates are of no use. Does that mean that even though I won some hackathon and have a certificate, there is no use of it.(I had won the Smart India Hackathon 2019 software edition😗😙)

**Comment by tanaypratap** [comment]
Hackathons are good. Certificates where you just hit the play button is not good.

See this post for more details.

https://www.linkedin.com/posts/activity-6654955895073673216-NsKL
