### ISSUE TITLE
Can I define the state in React inside constructor?

### ISSUE THREAD

**Issue by akulsr0** [tanaypratap/ama#89]
Hi Tanay, I watched your live session on Youtube where you defined the state as
state = {
}

I have some hands-on ReactNative there we do it inside a constructor, like this-

constructor(){
   super();
   this.state = {
   }
}

**Comment by gladydennyson** [comment]
Yes absolutely! Whenever your React activity is extending a component, the constructor is called before it is mounted. 
The methods are called in the following order
- constructor()
- static getDerivedStateFromProps()
- render()
- componentDidMount()

**So it is good practice to mention state inside the constructor like 
constructor()** 
{
super();
this.state = {
}
}

**Comment by tanaypratap** [comment]
Both are accepted practice. There's almost zero difference. So much so that
in Microsoft we don't use constructor anymore.
