### ISSUE TITLE
What is the importance of internships in 2nd year? Would it be okay, if I invest time in learning DS, Algo and other computer science related stuff?

### ISSUE THREAD

**Issue by Priyanka488** [tanaypratap/ama#9]

**Comment by tanaypratap** [comment]
In 2nd year, you should not go for internships. You should instead build your resume to get a better internship. 
For how to build a better resume, [watch this video on what to do in college.](https://www.youtube.com/playlist?list=PLzvhQUIpvvujXvcaIthycttSLChcP_rF2)

**Comment by tanaypratap** [comment]
@Priyanka488 I hope this helps. Let me know if I missed out on something.

Overall advice: Keep coding and creating projects on your own instead of wasting time in internships here and there.

**Comment by Priyanka488** [comment]
@tanaypratap Thank you for the guidance !  : )
