### ISSUE TITLE
It's about GitHub!

### ISSUE THREAD

**Issue by pranavbhat3105** [tanaypratap/ama#98]
If suppose I know js properly and I build some apps... How shall I put it on Git hub? And suppose if I upload it on Github will it open my code or the output ( The app or the website which I built?)

**Comment by gkanishk** [comment]
Yes, you can host pages on GitHub using GitHub pages, just make a repository upload your files and then go to your repository settings and scroll down to GitHub pages and select master branch in the source column you will get the link in which your page is hosted.

**Comment by gkanishk** [comment]
![image](https://user-images.githubusercontent.com/33570551/59147891-f70d3280-8a1e-11e9-94f1-baa8f584d83b.png)
 check this image for reference
